In [1]:
import pandas as pd

## Define function to inspect every tables basic info

In [2]:
def inspect_table(df, name):
    print("=" * 50)
    print(f"Table: {name}")
    print("=" * 50)

    print(f"Shape: {df.shape}")
    print("\nColumns:")
    print(df.columns.tolist())

    print("\nInfo:")
    df.info()

    print("\nSample:")
    display(df.head())

## read all tables for inspection

In [3]:
customer_df= pd.read_csv('../data/raw/olist_customers_dataset.csv')
inspect_table(customer_df, "Customers")

==================================================
Table: Customers
==================================================
Shape: (99441, 5)

Columns:
['customer_id', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state']

Info:
<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  str
 1   customer_unique_id        99441 non-null  str
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  str
 4   customer_state            99441 non-null  str
dtypes: int64(1), str(4)
memory usage: 11.0 MB

Sample:

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [4]:
geoloc_df = pd.read_csv('../data/raw/olist_geolocation_dataset.csv')
inspect_table(geoloc_df, "Geolocation")

==================================================
Table: Geolocation
==================================================
Shape: (1000163, 5)

Columns:
['geolocation_zip_code_prefix', 'geolocation_lat', 'geolocation_lng', 'geolocation_city', 'geolocation_state']

Info:
<class 'pandas.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  str
 4   geolocation_state            1000163 non-null  str
dtypes: float64(2), int64(1), str(2)
memory usage: 50.1 MB

Sample:

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

In [5]:
order_items_df = pd.read_csv('../data/raw/olist_order_items_dataset.csv')
inspect_table(order_items_df, "Order Items")

==================================================
Table: Order Items
==================================================
Shape: (112650, 7)

Columns:
['order_id', 'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date', 'price', 'freight_value']

Info:
<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  str
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  str
 3   seller_id            112650 non-null  str
 4   shipping_limit_date  112650 non-null  str
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), str(4)
memory usage: 18.4 MB

Sample:

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [6]:
order_payments_df = pd.read_csv('../data/raw/olist_order_payments_dataset.csv')
inspect_table(order_payments_df, "Order Payments")

==================================================
Table: Order Payments
==================================================
Shape: (103886, 5)

Columns:
['order_id', 'payment_sequential', 'payment_type', 'payment_installments', 'payment_value']

Info:
<class 'pandas.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  str
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  str
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), str(2)
memory usage: 8.1 MB

Sample:

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [7]:
order_reviews_df = pd.read_csv('../data/raw/olist_order_reviews_dataset.csv')
inspect_table(order_reviews_df, "Order Reviews")

==================================================
Table: Order Reviews
==================================================
Shape: (99224, 7)

Columns:
['review_id', 'order_id', 'review_score', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp']

Info:
<class 'pandas.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  str
 1   order_id                 99224 non-null  str
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  str
 4   review_comment_message   40977 non-null  str
 5   review_creation_date     99224 non-null  str
 6   review_answer_timestamp  99224 non-null  str
dtypes: int64(1), str(6)
memory usage: 17.8 MB

Sample:

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [8]:
order_df = pd.read_csv('../data/raw/olist_orders_dataset.csv')
inspect_table(order_df, "Orders")

==================================================
Table: Orders
==================================================
Shape: (99441, 8)

Columns:
['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']

Info:
<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 21.9 MB

Sample:

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [9]:
product_df = pd.read_csv('../data/raw/olist_products_dataset.csv')
inspect_table(product_df, "Products")

==================================================
Table: Products
==================================================
Shape: (32951, 9)

Columns:
['product_id', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']

Info:
<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  str
 1   product_category_name       32341 non-null  str
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), str(2)
memory usage: 3.7 MB

Sample:

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [10]:
seller_df = pd.read_csv('../data/raw/olist_sellers_dataset.csv')
inspect_table(seller_df, "Sellers")

==================================================
Table: Sellers
==================================================
Shape: (3095, 4)

Columns:
['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state']

Info:
<class 'pandas.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   str
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   str
 3   seller_state            3095 non-null   str
dtypes: int64(1), str(3)
memory usage: 230.3 KB

Sample:

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [11]:
category_df = pd.read_csv('../data/raw/product_category_name_translation.csv')
inspect_table(category_df, "Product Category Name Translation")

==================================================
Table: Product Category Name Translation
==================================================
Shape: (71, 2)

Columns:
['product_category_name', 'product_category_name_english']

Info:
<class 'pandas.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     str
 1   product_category_name_english  71 non-null     str
dtypes: str(2)
memory usage: 3.5 KB

Sample:

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [12]:
print(customer_df["customer_unique_id"].nunique())
print(product_df["product_id"].nunique())
print(product_df["product_category_name"].nunique())
print(order_df["order_id"].nunique())

96096
32951
73
99441

## Create the interaction dataset only for tables needed for recommendation by joining

In [13]:
interaction_df = (
    customer_df
    .merge(order_df, on="customer_id", how="inner")
    .merge(order_items_df, on="order_id", how="inner")
    .merge(product_df, on="product_id", how="left")
)

In [14]:
inspect_table(interaction_df, "Interaction")

==================================================
Table: Interaction
==================================================
Shape: (112650, 26)

Columns:
['customer_id', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state', 'order_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date', 'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date', 'price', 'freight_value', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']

Info:
<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 26 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   customer_id                    112650 non-null  str
 1   customer_unique_id             112650 non-null  str
 2   customer_zip_code_prefix       112650 non-null  int64
 3   customer_city                  112650 non-null  str
 4   customer_state                 112650 non-null  str
 5   order_id                       112650 non-null  str
 6   order_status                   112650 non-null  str
 7   order_purchase_timestamp       112650 non-null  str
 8   order_approved_at              112635 non-null  str
 9   order_delivered_carrier_date   111456 non-null  str
 10  order_delivered_customer_date  110196 non-null  str
 11  order_estimated_delivery_date  112650 non-null  str
 12  order_item_id                  112650 non-null  int64
 13  product_id                     112650 non-null  str
 14  seller_id                      112650 non-null  str
 15  shipping_limit_date            112650 non-null  str
 16  price                          112650 non-null  float64
 17  freight_value                  112650 non-null  float64
 18  product_category_name          111047 non-null  str
 19  product_name_lenght            111047 non-null  float64
 20  product_description_lenght     111047 non-null  float64
 21  product_photos_qty             111047 non-null  float64
 22  product_weight_g               112632 non-null  float64
 23  product_length_cm              112632 non-null  float64
 24  product_height_cm              112632 non-null  float64
 25  product_width_cm               112632 non-null  float64
dtypes: float64(9), int64(2), str(15)
memory usage: 55.8 MB

Sample:

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,...,price,freight_value,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,00e7ee1b050b8499577073aeb2a297a1,delivered,2017-05-16 15:05:35,2017-05-16 15:22:12,2017-05-23 10:47:57,...,124.99,21.88,moveis_escritorio,41.0,1141.0,1.0,8683.0,54.0,64.0,31.0
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP,29150127e6685892b6eab3eec79f59c7,delivered,2018-01-12 20:48:24,2018-01-12 20:58:32,2018-01-15 17:14:59,...,289.00,46.48,utilidades_domesticas,43.0,1002.0,3.0,10150.0,89.0,15.0,40.0
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP,b2059ed67ce144a36e2aa97d2c9e9ad2,delivered,2018-05-19 16:07:45,2018-05-20 16:19:10,2018-06-11 14:31:00,...,139.94,17.79,moveis_escritorio,55.0,955.0,1.0,8267.0,52.0,52.0,17.0
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP,951670f92359f4fe4a63112aa7306eba,delivered,2018-03-13 16:06:38,2018-03-13 17:29:19,2018-03-27 23:22:42,...,149.94,23.36,moveis_escritorio,48.0,1066.0,1.0,12160.0,56.0,51.0,28.0
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP,6b7d50bd145f6fc7f33cebabd7e49d0f,delivered,2018-07-29 09:51:30,2018-07-29 10:10:09,2018-07-30 15:16:00,...,230.00,22.25,casa_conforto,61.0,407.0,1.0,5200.0,45.0,15.0,35.0

## Orders per customer:

In [15]:
(
    interaction_df
    .groupby("customer_unique_id")["order_id"]
    .nunique()
    .sort_values(ascending=False)
)

customer_unique_id
8d50f5eadf50201ccdcedfb9e2ac8455    16
3e43e6105506432c953e165fb2acf44c     9
1b6c7548a2a1f9037c1fd3ddfed95f33     7
ca77025e7201e3b30c44b472ff346268     7
6469f99c1f9dfae7733b25662e7f1782     7
                                    ..
5656eb169546146caeab56c3ffc3d268     1
5656a8fabc8629ff96b2bc14f8c09a27     1
56560124a5cc70119deb685775639ea7     1
5655ee330a79bd1fd1e5fb220c2436dd     1
565b893de0c415f080aa45f57325454d     1
Name: order_id, Length: 95420, dtype: int64

## Products purchased per customer

In [16]:
(
    interaction_df
    .groupby("customer_unique_id")["product_id"]
    .nunique()
    .sort_values(ascending=False)
)

customer_unique_id
8d50f5eadf50201ccdcedfb9e2ac8455    15
3e43e6105506432c953e165fb2acf44c    13
1b6c7548a2a1f9037c1fd3ddfed95f33     9
ca77025e7201e3b30c44b472ff346268     9
c8ed31310fc440a3f8031b177f9842c3     8
                                    ..
5775984939803dfe2ef8bad0f4c63abb     1
57750363042d3964075f63e02f2a3f19     1
5774bddb63ba355a6b8a7d232a0b4d3f     1
57742ce9227b5281011a0b4249c83f0b     1
577a55f3f16b2ac437efb677258f317c     1
Name: product_id, Length: 95420, dtype: int64

## Categories purchased per customer:

In [17]:
(
    interaction_df
    .groupby("customer_unique_id")["product_category_name"]
    .nunique()
    .sort_values(ascending=False)
)

customer_unique_id
74cb1ad7e6d5674325c1f99b5ea30d82    5
47c1a3033b8b77b3ab6e109eb4d5fdf3    5
1b6c7548a2a1f9037c1fd3ddfed95f33    5
3e43e6105506432c953e165fb2acf44c    5
35ecdf6858edc6427223b64804cf028e    5
                                   ..
fbeff5c13e7e935d9e2dbe67de1f43c9    0
fb6ffdea3495cfb5236ef8dd1f18fbb1    0
fb88ebab2021f2706997dbf98a6790f5    0
fb3c613bce3dd56a126ccae1764704e0    0
fb0b0f23796b9dda6d428cac76466b8c    0
Name: product_category_name, Length: 95420, dtype: int64

## Customer Lifetime Spend:

In [18]:
(
    interaction_df
    .groupby("customer_unique_id")["price"]
    .sum()
    .sort_values(ascending=False)
)

customer_unique_id
0a0a92112bd4c708ca5fde585afaa872    13440.00
da122df9eeddfedc1dc1f5349a1a690c     7388.00
763c8b1c9c68a0229c42c9fc6f662b93     7160.00
dc4802a71eae9be1dd28f5d788ceb526     6735.00
459bef486812aa25204be022145caa62     6729.00
                                      ...
cf3839da0d9492ad151690b65f45d800        2.99
bd06ce0e06ad77a7f681f1a4960a3cc6        2.29
317cfc692e3f86c45c95697c61c853a6        2.20
b38211bd797f4fdd81a98b9d1754b606        0.85
d80730c15c647bc8f2ad77c908ba5ca9        0.85
Name: price, Length: 95420, dtype: float64

## Recommendation Matrix Feasibility:

In [19]:
interaction_df[
    ["customer_unique_id", "product_id"]
]

                      customer_unique_id                        product_id
0       861eff4711a542e4b93843c6dd7febb0  a9516a079e37a9c9c36b9b78b10169e8
1       290c77bc529b7ac935b93aa66c333dc3  4aa6014eceb682077f9dc4bffebc05b0
2       060e732b5b29e8181a18229c7b0b2b5e  bd07b66896d6f1494f5b86251848ced7
3       259dac757896d24d7702b9acbbff3f3c  a5647c44af977b148e0a3a4751a09e2e
4       345ecd01c38d18a9036ed96c73b8d066  9391a573abe00141c56e38d84d7d5b3b
...                                  ...                               ...
112645  1a29b476fee25c95fbafc67c5ac95cf8  ccb4503d9d43d245d3b295d0544f988b
112646  d52a67c98be1cf6a5c84435bd38d095d  9ede6b0570a75a4b9de4f383329f99ee
112647  e9f50caf99f032f0bf3c55141f019d99  7a5d2e1e131a860ae7d18f6fffa9d689
112648  73c2643a0a458b49f58cea58833b192e  f819f0c84a64f02d3a5606ca95edd272
112649  84732c5050c01db9b23e19ba39899398  017692475c1c954ff597feda05131d73

[112650 rows x 2 columns]

In [20]:
print(interaction_df.shape)

interaction_df[
    [
        "customer_unique_id",
        "order_id",
        "product_id",
        "product_category_name",
        "price"
    ]
].head()

(112650, 26)

,customer_unique_id,order_id,product_id,product_category_name,price
0,861eff4711a542e4b93843c6dd7febb0,00e7ee1b050b8499577073aeb2a297a1,a9516a079e37a9c9c36b9b78b10169e8,moveis_escritorio,124.99
1,290c77bc529b7ac935b93aa66c333dc3,29150127e6685892b6eab3eec79f59c7,4aa6014eceb682077f9dc4bffebc05b0,utilidades_domesticas,289.00
2,060e732b5b29e8181a18229c7b0b2b5e,b2059ed67ce144a36e2aa97d2c9e9ad2,bd07b66896d6f1494f5b86251848ced7,moveis_escritorio,139.94
3,259dac757896d24d7702b9acbbff3f3c,951670f92359f4fe4a63112aa7306eba,a5647c44af977b148e0a3a4751a09e2e,moveis_escritorio,149.94
4,345ecd01c38d18a9036ed96c73b8d066,6b7d50bd145f6fc7f33cebabd7e49d0f,9391a573abe00141c56e38d84d7d5b3b,casa_conforto,230.00

## Missing Product Categories

In [21]:
print(interaction_df["product_category_name"].isna().sum())

1603

## Duplicate Customer-Product Interactions

In [22]:
print(interaction_df[
    ["customer_unique_id", "product_id"]
].duplicated().sum())

10663

## Orders Per Customer

In [23]:
orders_per_customer = (
    interaction_df
    .groupby("customer_unique_id")["order_id"]
    .nunique()
)

orders_per_customer.describe()

count    95420.000000
mean         1.034018
std          0.211234
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max         16.000000
Name: order_id, dtype: float64

In [24]:
orders_per_customer.value_counts().head(20)

order_id
1     92507
2      2673
3       192
4        29
5         9
6         5
7         3
9         1
16        1
Name: count, dtype: int64

In [25]:
print(interaction_df["customer_unique_id"].nunique())

print(interaction_df["product_id"].nunique())

print(interaction_df["product_category_name"].nunique())

print(interaction_df["product_category_name"].isna().sum())

print(interaction_df[
    ["customer_unique_id", "product_id"]
].duplicated().sum())

95420
32951
73
1603
10663

In [26]:
order_items_df["order_item_id"].value_counts().sort_index()

order_item_id
1     98666
2      9803
3      2287
4       965
5       460
6       256
7        58
8        36
9        28
10       25
11       17
12       13
13        8
14        7
15        5
16        3
17        3
18        3
19        3
20        3
21        1
Name: count, dtype: int64

In [27]:
order_items_df[
    order_items_df["order_item_id"] > 1
]

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
14,0008288aa423d2a3f00fcb17cd7d8719,2,368c6c730842d78016ad823897a372db,1f50f920176fa81dab994f9023523100,2018-02-21 02:55:52,49.90,13.37
33,00143d0f86d6fbd9f9b38ab440ac16f5,2,e95ee6822b66ac6058e2e4aff656071a,a17f621c590ea0fab3d5d883e1630ec6,2017-10-20 16:07:52,21.33,15.10
34,00143d0f86d6fbd9f9b38ab440ac16f5,3,e95ee6822b66ac6058e2e4aff656071a,a17f621c590ea0fab3d5d883e1630ec6,2017-10-20 16:07:52,21.33,15.10
43,001ab0a7578dd66cd4b0a71f5b6e1e41,2,0b0172eb0fd18479d29c3bc122c058c2,5656537e588803a555b8eb41f07a944b,2018-01-04 02:33:42,24.89,17.63
44,001ab0a7578dd66cd4b0a71f5b6e1e41,3,0b0172eb0fd18479d29c3bc122c058c2,5656537e588803a555b8eb41f07a944b,2018-01-04 02:33:42,24.89,17.63
...,...,...,...,...,...,...,...
112617,ffecd5a79a0084f6a592288c67e3c298,3,50fd2b788dc166edd20512370dac54df,8b321bb669392f5163d04c59e235e066,2018-03-05 20:15:27,21.90,15.79
112635,fff8287bbae429a99bb7e8c21d151c41,2,bee2e070c39f3dd2f6883a17a5f0da45,4e922959ae960d389249c378d1c939f5,2018-03-27 12:29:22,180.00,48.14
112641,fffb9224b6fc7c43ebb0904318b10b5f,2,43423cdffde7fda63d0414ed38c11a73,b1fc4f64df5a0e8b6913ab38803c57a9,2017-11-03 02:55:58,55.00,34.19
112642,fffb9224b6fc7c43ebb0904318b10b5f,3,43423cdffde7fda63d0414ed38c11a73,b1fc4f64df5a0e8b6913ab38803c57a9,2017-11-03 02:55:58,55.00,34.19
112643,fffb9224b6fc7c43ebb0904318b10b5f,4,43423cdffde7fda63d0414ed38c11a73,b1fc4f64df5a0e8b6913ab38803c57a9,2017-11-03 02:55:58,55.00,34.19

## Total Products Purchased Per Customer

In [28]:
products_per_customer = (
    interaction_df
    .groupby("customer_unique_id")["product_id"]
    .count()
)

products_per_customer.describe()

count    95420.00000
mean         1.18057
std          0.62145
min          1.00000
25%          1.00000
50%          1.00000
75%          1.00000
max         24.00000
Name: product_id, dtype: float64

## Unique Products Purchased Per Customer

In [29]:
unique_products_per_customer = (
    interaction_df
    .groupby("customer_unique_id")["product_id"]
    .nunique()
)

unique_products_per_customer.describe()

count    95420.000000
mean         1.068822
std          0.316810
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max         15.000000
Name: product_id, dtype: float64

## How many products exist inside each order?

In [30]:
products_per_order = (
    interaction_df
    .groupby("order_id")["product_id"]
    .count()
)

products_per_order.describe()

count    98666.000000
mean         1.141731
std          0.538452
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max         21.000000
Name: product_id, dtype: float64

In [31]:
products_per_order.value_counts().sort_index()

product_id
1     88863
2      7516
3      1322
4       505
5       204
6       198
7        22
8         8
9         3
10        8
11        4
12        5
13        1
14        2
15        2
20        2
21        1
Name: count, dtype: int64

## Most Purchased Categories

In [32]:
interaction_df["product_category_name"]\
    .value_counts()\
    .head(20)

product_category_name
cama_mesa_banho                11115
beleza_saude                    9670
esporte_lazer                   8641
moveis_decoracao                8334
informatica_acessorios          7827
utilidades_domesticas           6964
relogios_presentes              5991
telefonia                       4545
ferramentas_jardim              4347
automotivo                      4235
brinquedos                      4117
cool_stuff                      3796
perfumaria                      3419
bebes                           3065
eletronicos                     2767
papelaria                       2517
fashion_bolsas_e_acessorios     2031
pet_shop                        1947
moveis_escritorio               1691
consoles_games                  1137
Name: count, dtype: int64

## Categories With Most Unique Products

In [33]:
interaction_df.groupby(
    "product_category_name"
)["product_id"].nunique()\
 .sort_values(ascending=False)\
 .head(20)

product_category_name
cama_mesa_banho                      3029
esporte_lazer                        2867
moveis_decoracao                     2657
beleza_saude                         2444
utilidades_domesticas                2335
automotivo                           1900
informatica_acessorios               1639
brinquedos                           1411
relogios_presentes                   1329
telefonia                            1134
bebes                                 919
perfumaria                            868
papelaria                             849
fashion_bolsas_e_acessorios           849
cool_stuff                            789
ferramentas_jardim                    753
pet_shop                              719
eletronicos                           517
construcao_ferramentas_construcao     400
eletrodomesticos                      370
Name: product_id, dtype: int64

## Average Price By Category

In [34]:
interaction_df.groupby(
    "product_category_name"
)["price"].mean()\
 .sort_values(ascending=False)\
 .head(20)

product_category_name
pcs                                               1098.340542
portateis_casa_forno_e_cafe                        624.285658
eletrodomesticos_2                                 476.124958
agro_industria_e_comercio                          342.124858
instrumentos_musicais                              281.616000
eletroportateis                                    280.778468
portateis_cozinha_e_preparadores_de_alimentos      264.568667
telefonia_fixa                                     225.693182
construcao_ferramentas_seguranca                   208.992371
relogios_presentes                                 201.135984
climatizacao                                       185.269226
moveis_quarto                                      183.750275
pc_gamer                                           171.772222
cool_stuff                                         167.357969
moveis_cozinha_area_de_servico_jantar_e_jardim     164.869644
moveis_escritorio                                  162.011059
musica                                             158.798684
construcao_ferramentas_construcao                  155.734758
construcao_ferramentas_ferramentas                 154.407282
industria_comercio_e_negocios                      148.020933
Name: price, dtype: float64

## Customer Spend Analysis

In [35]:
customer_spend = (
    interaction_df
    .groupby("customer_unique_id")["price"]
    .sum()
)

In [36]:
customer_spend.describe()

count    95420.000000
mean       142.440198
std        217.656355
min          0.850000
25%         47.900000
50%         89.900000
75%        155.000000
max      13440.000000
Name: price, dtype: float64

## Product Purchase Analysis

In [37]:
customer_category_diversity = (
    interaction_df
    .groupby("customer_unique_id")["product_category_name"]
    .nunique()
)

In [38]:
products_per_customer.describe()

count    95420.00000
mean         1.18057
std          0.62145
min          1.00000
25%          1.00000
50%          1.00000
75%          1.00000
max         24.00000
Name: product_id, dtype: float64

## Top Selling Products

In [39]:
top_products = (
    interaction_df["product_id"]
    .value_counts()
    .head(20)
)

top_products

product_id
aca2eb7d00ea1a7b8ebd4e68314663af    527
99a4788cb24856965c36a24e339b6058    488
422879e10f46682990de24d770e7f83d    484
389d119b48cf3043d311335e499d9c6b    392
368c6c730842d78016ad823897a372db    388
53759a2ecddad2bb87a079a1f1519f73    373
d1c427060a0f73f6b889a5c7c61f2ac4    343
53b36df67ebb7c41585e8d54d6772e08    323
154e7e31ebfa092203795c972e5804a6    281
3dd2a17168ec895c781a9191c1e95ad7    274
2b4609f8948be18874494203496bc318    260
7c1bd920dbdf22470b68bde975dd3ccf    231
a62e25e09e05e6faf31d90c6ec1aa3d1    226
5a848e4ab52fd5445cdc07aab1c40e48    197
bb50f2e236e5eea0100680137654686c    195
e0d64dcfaa3b6db5c54ca298ae101d05    194
42a2c92a0979a949ca4ea89ec5c7b934    183
e53e557d5a159f5aa2c5e995dfdf244b    183
b532349fe46b38fbc7bb3914c1bdae07    169
35afc973633aaeb6b877ff57b2793310    165
Name: count, dtype: int64

## Product Sales Distribution

In [40]:
product_sales = (
    interaction_df
    .groupby("product_id")
    .size()
)

product_sales.describe()

count    32951.000000
mean         3.418713
std         10.619709
min          1.000000
25%          1.000000
50%          1.000000
75%          3.000000
max        527.000000
dtype: float64

## Category Revenue

In [41]:
category_revenue = (
    interaction_df
    .groupby("product_category_name")["price"]
    .sum()
    .sort_values(ascending=False)
)

category_revenue.head(20)

product_category_name
beleza_saude              1258681.34
relogios_presentes        1205005.68
cama_mesa_banho           1036988.68
esporte_lazer              988048.97
informatica_acessorios     911954.32
moveis_decoracao           729762.49
cool_stuff                 635290.85
utilidades_domesticas      632248.66
automotivo                 592720.11
ferramentas_jardim         485256.46
brinquedos                 483946.60
bebes                      411764.89
perfumaria                 399124.87
telefonia                  323667.53
moveis_escritorio          273960.70
papelaria                  230943.23
pcs                        222963.13
pet_shop                   214315.41
instrumentos_musicais      191498.88
eletroportateis            190648.58
Name: price, dtype: float64

## Category Purchase Frequency

In [42]:
category_frequency = (
    interaction_df
    .groupby("product_category_name")
    .size()
    .sort_values(ascending=False)
)

category_frequency.head(20)

product_category_name
cama_mesa_banho                11115
beleza_saude                    9670
esporte_lazer                   8641
moveis_decoracao                8334
informatica_acessorios          7827
utilidades_domesticas           6964
relogios_presentes              5991
telefonia                       4545
ferramentas_jardim              4347
automotivo                      4235
brinquedos                      4117
cool_stuff                      3796
perfumaria                      3419
bebes                           3065
eletronicos                     2767
papelaria                       2517
fashion_bolsas_e_acessorios     2031
pet_shop                        1947
moveis_escritorio               1691
consoles_games                  1137
dtype: int64

## Category Diversity Per Customer

In [43]:
customer_category_diversity = (
    interaction_df
    .groupby("customer_unique_id")["product_category_name"]
    .nunique()
)

customer_category_diversity.describe()

count    95420.000000
mean         1.011004
std          0.205165
min          0.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          5.000000
Name: product_category_name, dtype: float64

## Purchase Timeline

In [44]:
interaction_df["order_purchase_timestamp"] = pd.to_datetime(
    interaction_df["order_purchase_timestamp"]
)

interaction_df.set_index(
    "order_purchase_timestamp"
).resample("ME")["order_id"].count()

order_purchase_timestamp
2016-09-30       6
2016-10-31     363
2016-11-30       0
2016-12-31       1
2017-01-31     955
2017-02-28    1951
2017-03-31    3000
2017-04-30    2684
2017-05-31    4136
2017-06-30    3583
2017-07-31    4519
2017-08-31    4910
2017-09-30    4831
2017-10-31    5322
2017-11-30    8665
2017-12-31    6308
2018-01-31    8208
2018-02-28    7672
2018-03-31    8217
2018-04-30    7975
2018-05-31    7925
2018-06-30    7078
2018-07-31    7092
2018-08-31    7248
2018-09-30       1
Freq: ME, Name: order_id, dtype: int64

## Customer Spend Segments

In [45]:
customer_spend.quantile(
    [0.25, 0.50, 0.75, 0.90, 0.95, 0.99]
)

0.25      47.9000
0.50      89.9000
0.75     155.0000
0.90     284.0000
0.95     422.0000
0.99    1013.5934
Name: price, dtype: float64

## Products with enough interaction history

In [46]:
eligible_products = (
    product_sales[product_sales >= 5]
)

eligible_products.shape

(4832,)

In [47]:
eligible_products.describe()

count    4832.000000
mean       14.240480
std        25.050083
min         5.000000
25%         6.000000
50%         8.000000
75%        13.000000
max       527.000000
dtype: float64

In [48]:
model_df = interaction_df[
    [
        "customer_unique_id",
        "product_id",
        "product_category_name",
        "price",
        "order_purchase_timestamp"
    ]
].copy()

In [49]:
model_df = model_df[
    model_df["product_id"].isin(
        eligible_products.index
    )
]

In [50]:
print(model_df.shape)

print(model_df["customer_unique_id"].nunique())

print(model_df["product_id"].nunique())

(68810, 5)
58678
4832

## Finding most popular products by purchase count

In [51]:
popular_products = (
    model_df
    .groupby("product_id")
    .size()
    .reset_index(name="purchase_count")
    .sort_values(
        "purchase_count",
        ascending=False
    )
)

popular_products.head(20)

                            product_id  purchase_count
3275  aca2eb7d00ea1a7b8ebd4e68314663af             527
2901  99a4788cb24856965c36a24e339b6058             488
1273  422879e10f46682990de24d770e7f83d             484
1090  389d119b48cf3043d311335e499d9c6b             392
1038  368c6c730842d78016ad823897a372db             388
1611  53759a2ecddad2bb87a079a1f1519f73             373
3982  d1c427060a0f73f6b889a5c7c61f2ac4             343
1616  53b36df67ebb7c41585e8d54d6772e08             323
417   154e7e31ebfa092203795c972e5804a6             281
1191  3dd2a17168ec895c781a9191c1e95ad7             274
834   2b4609f8948be18874494203496bc318             260
2379  7c1bd920dbdf22470b68bde975dd3ccf             231
3151  a62e25e09e05e6faf31d90c6ec1aa3d1             226
1762  5a848e4ab52fd5445cdc07aab1c40e48             197
3555  bb50f2e236e5eea0100680137654686c             195
4228  e0d64dcfaa3b6db5c54ca298ae101d05             194
4309  e53e557d5a159f5aa2c5e995dfdf244b             183
1289  42a2c92a0979a949ca4ea89ec5c7b934             183
3439  b532349fe46b38fbc7bb3914c1bdae07             169
1025  35afc973633aaeb6b877ff57b2793310             165

In [52]:
product_metadata = (
    interaction_df[
        [
            "product_id",
            "product_category_name"
        ]
    ]
    .drop_duplicates()
)

popular_products = popular_products.merge(
    product_metadata,
    on="product_id",
    how="left"
)

In [53]:
TOP_K = 10

recommendations = (
    popular_products
    .head(TOP_K)
)

recommendations

                         product_id  purchase_count   product_category_name
0  aca2eb7d00ea1a7b8ebd4e68314663af             527        moveis_decoracao
1  99a4788cb24856965c36a24e339b6058             488         cama_mesa_banho
2  422879e10f46682990de24d770e7f83d             484      ferramentas_jardim
3  389d119b48cf3043d311335e499d9c6b             392      ferramentas_jardim
4  368c6c730842d78016ad823897a372db             388      ferramentas_jardim
5  53759a2ecddad2bb87a079a1f1519f73             373      ferramentas_jardim
6  d1c427060a0f73f6b889a5c7c61f2ac4             343  informatica_acessorios
7  53b36df67ebb7c41585e8d54d6772e08             323      relogios_presentes
8  154e7e31ebfa092203795c972e5804a6             281            beleza_saude
9  3dd2a17168ec895c781a9191c1e95ad7             274  informatica_acessorios

## Storing in parquet format

In [54]:
recommendations.to_parquet(
    "../artifacts/popularity_recommendations.parquet",
    engine="pyarrow",
    index=False
)

In [55]:
popular_products = (
    model_df
    .groupby("product_id")
    .size()
    .reset_index(name="purchase_count")
    .sort_values(
        "purchase_count",
        ascending=False
    )
)

popular_products.head(20)

                            product_id  purchase_count
3275  aca2eb7d00ea1a7b8ebd4e68314663af             527
2901  99a4788cb24856965c36a24e339b6058             488
1273  422879e10f46682990de24d770e7f83d             484
1090  389d119b48cf3043d311335e499d9c6b             392
1038  368c6c730842d78016ad823897a372db             388
1611  53759a2ecddad2bb87a079a1f1519f73             373
3982  d1c427060a0f73f6b889a5c7c61f2ac4             343
1616  53b36df67ebb7c41585e8d54d6772e08             323
417   154e7e31ebfa092203795c972e5804a6             281
1191  3dd2a17168ec895c781a9191c1e95ad7             274
834   2b4609f8948be18874494203496bc318             260
2379  7c1bd920dbdf22470b68bde975dd3ccf             231
3151  a62e25e09e05e6faf31d90c6ec1aa3d1             226
1762  5a848e4ab52fd5445cdc07aab1c40e48             197
3555  bb50f2e236e5eea0100680137654686c             195
4228  e0d64dcfaa3b6db5c54ca298ae101d05             194
4309  e53e557d5a159f5aa2c5e995dfdf244b             183
1289  42a2c92a0979a949ca4ea89ec5c7b934             183
3439  b532349fe46b38fbc7bb3914c1bdae07             169
1025  35afc973633aaeb6b877ff57b2793310             165

In [56]:
popular_products = (
    popular_products
    .merge(
        product_df[
            [
                "product_id",
                "product_category_name"
            ]
        ],
        on="product_id",
        how="left"
    )
)

In [57]:
popular_products.head(20)

                          product_id  purchase_count   product_category_name
0   aca2eb7d00ea1a7b8ebd4e68314663af             527        moveis_decoracao
1   99a4788cb24856965c36a24e339b6058             488         cama_mesa_banho
2   422879e10f46682990de24d770e7f83d             484      ferramentas_jardim
3   389d119b48cf3043d311335e499d9c6b             392      ferramentas_jardim
4   368c6c730842d78016ad823897a372db             388      ferramentas_jardim
5   53759a2ecddad2bb87a079a1f1519f73             373      ferramentas_jardim
6   d1c427060a0f73f6b889a5c7c61f2ac4             343  informatica_acessorios
7   53b36df67ebb7c41585e8d54d6772e08             323      relogios_presentes
8   154e7e31ebfa092203795c972e5804a6             281            beleza_saude
9   3dd2a17168ec895c781a9191c1e95ad7             274  informatica_acessorios
10  2b4609f8948be18874494203496bc318             260            beleza_saude
11  7c1bd920dbdf22470b68bde975dd3ccf             231            beleza_saude
12  a62e25e09e05e6faf31d90c6ec1aa3d1             226      relogios_presentes
13  5a848e4ab52fd5445cdc07aab1c40e48             197                     NaN
14  bb50f2e236e5eea0100680137654686c             195            beleza_saude
15  e0d64dcfaa3b6db5c54ca298ae101d05             194      relogios_presentes
16  e53e557d5a159f5aa2c5e995dfdf244b             183  informatica_acessorios
17  42a2c92a0979a949ca4ea89ec5c7b934             183   utilidades_domesticas
18  b532349fe46b38fbc7bb3914c1bdae07             169        moveis_decoracao
19  35afc973633aaeb6b877ff57b2793310             165           casa_conforto

In [58]:
popular_products["popularity_score"] = (
    popular_products["purchase_count"]
    /
    popular_products["purchase_count"].max()
)

In [59]:
popular_products.head(20)

,product_id,purchase_count,product_category_name,popularity_score
0,aca2eb7d00ea1a7b8ebd4e68314663af,527,moveis_decoracao,1.000000
1,99a4788cb24856965c36a24e339b6058,488,cama_mesa_banho,0.925996
2,422879e10f46682990de24d770e7f83d,484,ferramentas_jardim,0.918406
3,389d119b48cf3043d311335e499d9c6b,392,ferramentas_jardim,0.743833
4,368c6c730842d78016ad823897a372db,388,ferramentas_jardim,0.736243
5,53759a2ecddad2bb87a079a1f1519f73,373,ferramentas_jardim,0.707780
6,d1c427060a0f73f6b889a5c7c61f2ac4,343,informatica_acessorios,0.650854
7,53b36df67ebb7c41585e8d54d6772e08,323,relogios_presentes,0.612903
8,154e7e31ebfa092203795c972e5804a6,281,beleza_saude,0.533207
9,3dd2a17168ec895c781a9191c1e95ad7,274,informatica_acessorios,0.519924
10,2b4609f8948be18874494203496bc318,260,beleza_saude,0.493359
11,7c1bd920dbdf22470b68bde975dd3ccf,231,beleza_saude,0.438330
12,a62e25e09e05e6faf31d90c6ec1aa3d1,226,relogios_presentes,0.428843
13,5a848e4ab52fd5445cdc07aab1c40e48,197,NaN,0.373814
14,bb50f2e236e5eea0100680137654686c,195,beleza_saude,0.370019
15,e0d64dcfaa3b6db5c54ca298ae101d05,194,relogios_presentes,0.368121
16,e53e557d5a159f5aa2c5e995dfdf244b,183,informatica_acessorios,0.347249
17,42a2c92a0979a949ca4ea89ec5c7b934,183,utilidades_domesticas,0.347249
18,b532349fe46b38fbc7bb3914c1bdae07,169,moveis_decoracao,0.320683
19,35afc973633aaeb6b877ff57b2793310,165,casa_conforto,0.313093

In [60]:
popular_products.to_parquet(
    "../artifacts/popularity_products.parquet",
    index=False
)

In [61]:
import pandas as pd

saved_df = pd.read_parquet(
    "../artifacts/popularity_products.parquet"
)

saved_df.head()

,product_id,purchase_count,product_category_name,popularity_score
0,aca2eb7d00ea1a7b8ebd4e68314663af,527,moveis_decoracao,1.000000
1,99a4788cb24856965c36a24e339b6058,488,cama_mesa_banho,0.925996
2,422879e10f46682990de24d770e7f83d,484,ferramentas_jardim,0.918406
3,389d119b48cf3043d311335e499d9c6b,392,ferramentas_jardim,0.743833
4,368c6c730842d78016ad823897a372db,388,ferramentas_jardim,0.736243

In [62]:
print(
    model_df["order_purchase_timestamp"].min()
)

print(
    model_df["order_purchase_timestamp"].max()
)

2016-09-04 21:15:19
2018-08-29 15:00:37

In [63]:
from pathlib import Path

Path("../data/processed").mkdir(
    parents=True,
    exist_ok=True
)

model_df.to_parquet(
    "../data/processed/model_df.parquet",
    index=False
)

In [64]:
saved_model_df = pd.read_parquet(
    "../data/processed/model_df.parquet"
)

saved_model_df.shape

(68810, 5)